function [diff] = get_diff(vr,i,j,t,min_i, min_j,max_i,max_j)
    if i == max_i
        if j == max_j
    
            diff = nanmean(abs([vr(i,j,t) - vr(i, j-1,t),...
                vr(i,j,t) - vr(i-1, j-1,t),...
                vr(i,j,t) - vr(i-1, j, t)]));

        elseif j == min_j
                
            diff = nanmean(abs([vr(i,j,t) - vr(i, j+1, t),...
                vr(i,j,t) - vr(i-1, j, t),...
                vr(i,j,t) - vr(i-1, j+1, t)]));
        else
    
            diff = nanmean(abs([vr(i,j,t) - vr(i, j-1,t),...
                vr(i,j,t) - vr(i, j+1, t),...
                vr(i,j,t) - vr(i-1, j-1,t),...
                vr(i,j,t) - vr(i-1, j, t),...
                vr(i,j,t) - vr(i-1, j+1, t)]));
        end

    elseif i == min_i
        if j == min_j

            diff = nanmean(abs([vr(i,j,t) - vr(i, j+1, t),...
                vr(i,j,t) - vr(i+1, j, t),...
                vr(i,j,t) - vr(i+1, j+1, t)]));
        elseif j==max_j
    
            diff = nanmean(abs([vr(i,j,t) - vr(i, j-1,t),...
                vr(i,j,t) - vr(i+1, j, t),...
                vr(i,j,t) - vr(i+1, j-1, t)]));
        else
            diff = nanmean(abs([vr(i,j,t) - vr(i, j-1,t),...
                vr(i,j,t) - vr(i, j+1, t),...
                vr(i,j,t) - vr(i+1, j, t),...
                vr(i,j,t) - vr(i+1, j-1, t),...
                vr(i,j,t) - vr(i+1, j+1, t)]));
        end
    
    elseif j== max_j
    
        diff = nanmean(abs([vr(i,j,t) - vr(i, j-1,t),...
            vr(i,j,t) - vr(i-1, j-1,t),...
            vr(i,j,t) - vr(i-1, j, t),...
            vr(i,j,t) - vr(i+1, j, t),...
            vr(i,j,t) - vr(i+1, j-1, t)]));

    elseif j == min_j
        diff = nanmean(abs([vr(i,j,t) - vr(i, j+1, t),...
            vr(i,j,t) - vr(i-1, j, t),...
            vr(i,j,t) - vr(i-1, j+1, t),...
            vr(i,j,t) - vr(i+1, j, t),...
            vr(i,j,t) - vr(i+1, j+1, t)]));
    
    else

        diff = nanmean(abs([vr(i,j,t) - vr(i, j-1,t),...
            vr(i,j,t) - vr(i, j+1, t),...
            vr(i,j,t) - vr(i-1, j-1,t),...
            vr(i,j,t) - vr(i-1, j, t),...
            vr(i,j,t) - vr(i-1, j+1, t),...
            vr(i,j,t) - vr(i+1, j, t),...
            vr(i,j,t) - vr(i+1, j-1, t),...
            vr(i,j,t) - vr(i+1, j+1, t)]));
    end


end