function [lambda,deltatransf,A,meantransf,exitflaglambda]=estimate_transfo_cov_ml(x,y,z,lambda0,A0,delta0,lagclass,nphi,znormalmin,znormalmax,intznormal,estimatelambda,estimatedelta,estimateanisotropy,exactness,exactnesscov,options)
%
%  Copyright (C) 2009 Gunter Spöck, email: gunter.spoeck@uni-klu.ac.at
%
%  This program is free software; you can redistribute it and/or modify it
%  under the terms of the GNU General Public License as published by the
%  Free Software Foundation; either version 2 of the License, or (at your
%  option) any later version.
%
%  This program is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
%  See the GNU General Public License for more details.
%
%  You should have received a copy of the GNU General Public License along
%  with this program; if not, write to the Free Software Foundation, Inc.,
%  51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
%
%  On Debian GNU/Linux systems, the complete text of the GNU General
%  Public License can be found in /usr/share/common-licenses/GPL-2.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  [lambda,deltatransf,A,meantransf,exitflaglambda]=estimate_transfo_cov_ml(x,y,z,lambda0,A0,delta0,lagclass,nphi,znormalmin,znormalmax,intznornal,estimatelambda,estimatedelta,estimateanisotropy,exactness,exactnesscov,options)
%
%  calculates the Box-Cox-transform of the data in z by means of maximum
%  likelihood.  Also the covariance function assumed to be geometric anisotropic 
%  is estimated.
%
%  Remark: It may happen that you must change the parameters in the
%  function optimset in order to speed up convergence of the optimization
%  routines. Furthermore it can become necessary to adjust the upper and 
%  lower bounds in the function fmincon. The same is true for the functions
%  weightedleastsquares.m and weightedleastsquaresaniso.m, that are called
%  by this function.
%
%  Inputs:
%
%  x...................the x-coordinates
%
%  y...................the y-coordinates
%
%  z...................a column-vector containing the data to be 
%                      transformed to normality
%
%  lambda0.............initial value for the calculation of the
%                      Box-Cox-parameter 
%
%  A0..................initial value for the transformation matrix
%
%  delta0..............initial value for the covariance parameters 
%                      =[nugget, sill, exp. range, Gaussian range, mixing parameter]
%
%  lagclass............lags for empirical variogram
%
%  nphi................a number giving the number of lagclasses in
%                      direction of the angle
%
%  znormalmin..........minimum z for the Gaussian data
%
%  znormalmax..........maximum z for the Gaussian data
%
%  intznormal..........intervallength for znormalmin:intznormal:znormalmax
%
%  estimatelambda......if it is 1, the Box-Cox or log-log transformation is estimated.
%
%  estimatedelta.......a vector of length 5 of 0's and 1's indicating what
%                      parameters of the covariance function should be
%                      estimated
%
%  estimateanisotropy..if it is 1, the anisotropy is estimated.
%
%  exactness...........positiv number giving the exactness
%                      of the likelihood (termination criterion)
% 
%  exactnesscov........positiv number giving the exactness
%                      of the estimated covariance parameters and anisotropy
%                      parameters (termination criterion)
%
%  options.............object generated by the function optimset
%
%  Outputs:
%
%  lambda.............the estimated Box-Cox-parameter
%
%  deltatransf........the estimated covariance parameters
%
%  A..................transformation matrix:  A=[a1 a3; a2 a4]
%
%  meantransf.........the mean of the Gaussian randomfield
%
%  exitflaglambda.....is 1 if the algorithm has converged, else it is 0
%
%  Example:
% 
%  options=optimset('LargeScale','on','MaxFunEvals',200,'TolFun',1e-3,'MaxIter',100);
%  [lambda0BoxGomeliso,delta0BoxGomeliso]=estimate_transfo_cov_ml(Gomel.x,Gomel.y,Gomel.zaver,0,[1,0;0,1],[0,2.4,80,80,0.6],0:15:150,10,-20,20,0.01,1,[1,1,1,1,1],0,0.001,0.001,options);
%
%  [lambda0BoxGomelaniso,delta0BoxGomelaniso,A0BoxGomelaniso]=estimate_transfo_cov_ml(Gomel.x,Gomel.y,Gomel.zaver,0,[1,0;0,1],[0,2.4,80,80,0.6],0:15:150,10,-20,20,0.01,1,[1,1,1,1,1],1,0.001,0.001,options);
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
delta1=delta0(estimatedelta==0);
zzz=0;
A=A0;
A = reshape(A,2,2);
A0=A;
%Fitting to normal distribution using the function criterium to estimate
%the starting value for lambda
options0=optimset('LargeScale','off','MaxFunEvals',50000000000,'MaxIter',50000000000);
if estimatelambda==1
   zz=znormalmin:intznormal:znormalmax;
   [lambd,zz,exitflag1]=fminunc(@criterium,[0.5*(znormalmin+znormalmax),0.5*sqrt(((znormalmax-znormalmin)/8)*((znormalmax-znormalmin)/8)),lambda0],options0,z,zz);
   clear zz
   lambda=lambd(3);   
else
   lambda=lambda0;
   exitflag1=1;
end   

znormallambda=transform(z,lambda);  
if estimateanisotropy==1
  empvario= empvariogramaniso(x,y,znormallambda,lagclass,nphi);
  %WeightedLeastSquares Estimate to find the starting values for delta & A
  disp('weightedleastsquaresaniso')
  [delta,A,exitflag2]=weightedleastsquaresaniso(empvario,delta0(1),delta0(2),delta0(3),delta0(4),delta0(5),A,estimatedelta,estimateanisotropy,exactnesscov); %%%
  
        n=length(z);
        xynew=A*[x';y'];
        xnew=xynew(1,:)';
        ynew=xynew(2,:)';
        delta=real(delta);
else
        n=length(z);
        xynew=A*[x';y'];
        xnew=xynew(1,:)';
        ynew=xynew(2,:)';
        exitflag2=1;
        empvario= empvariogram(xnew,ynew,znormallambda,lagclass);
        [delta,exitflag2]=weightedleastsquares(empvario,delta0(1),delta0(2),delta0(3),delta0(4),delta0(5),estimatedelta); %%%
        delta=real(delta);
end        
     k=0;
     likeold=0;
       for j=1:50
       k=k+1;
       if estimatelambda==1
       %Maximum Likelihood Estimate for Lambda 
       disp('likelilambda')
       [lambda,zzz,exitflag31]=fmincon(@likely,lambda,[],[],[],[],-2.5,2.5,[],options,xnew,ynew,z,delta);
       exitflag31;
       else
       exitflag31=1;
       lambda=lambda0;
       end
       
       if exitflag31<=0
          exitflag3=0;
          exitflag33=0;
          exitflag34=0;
          exitflag31=0;
          exitflag33=0;
          exitflag34=0;
          exitflag1=0;
          lambda=0;
          delta=[0,0,0,0,0];
          A=[1,0,0,1];
          break;
       end 
       
       znormallambda=transform(z,lambda);
       %Maximum Likelihood Estimate for Delta
       disp('likelidelta')
       [delta,zzz,exitflag33]=fmincon(@likely1,delta,[],[],[],[],[0.0001,0.0001,0.0001,0.0001,0.0001],[10,10,200000,200000,0.9999],[],options,xnew,ynew,z,lambda,delta1,estimatedelta);
       delta(estimatedelta==0)=delta1;
       delta=real(delta);
       %exitflag33=1;
       if exitflag33<=0
          exitflag3=0;
          exitflag34=0;
          exitflag31=0;
          exitflag33=0;
          exitflag34=0;
          exitflag1=0;
          lambda=0;
          delta=[0,0,0,0,0];
          A=[1,0,0,1];
          break;
       end
       if delta(2)<0
          exitflag33=0;
          exitflag3=0;
          exitflag34=0;
          exitflag31=0;
          exitflag33=0;
          exitflag34=0;
          exitflag1=0;
          delta=[0,0,0,0,0];
          A=[1,0;0,1];
          lambda=0;
          break;
       end
       if estimateanisotropy==1
       %Maximum Likelihood Estimate for A
       disp('likeliA')
       [A,zzz,exitflag34]=fmincon(@likely2,A,[],[],[],[],[-100,-100,-100,-100],[100,100,100,100],[],options,x,y,z,lambda,delta);
       %exitflag34=1;
       A=(reshape(A,2,2));
       n=length(z);
       xynew=A*[x';y'];
       xnew=xynew(1,:)';
       ynew=xynew(2,:)';
       if exitflag34<=0
          exitflag3=0;
          exitflag31=0;
          exitflag33=0;
          exitflag34=0;
          exitflag1=0;
          lambda=0;
          delta=[0,0,0,0,0];
          A=[1,0;0,1];
          break;
       end
       else
           exitflag34=1;
           A=A0;
       end  
      n=length(z);
      A=reshape(A,2,2);
  
      if estimatelambda==0
          lambda=lambda0;
      end  
     
      if abs(zzz-likeold)<=exactness
          break;
      else
          likeold=zzz;
      end
      
     end
     exitflag3=(exitflag31&exitflag33&exitflag34&exitflag1);
     if k>=50
         exitflag3=0;
     end   
   
   exitflag31=0;
   exitflag33=0;
   exitflag34=0;
   exitflag1=0;

%Code for plotting the anisotropic axes:
figure(5)
AAA=(reshape(A,2,2));
AAA=AAA'*AAA;
[V,D]=eig(AAA);
V=V*D;
V
plot([-5,5],[-5,5],'.w')
line([0,V(1,1)],[0,V(2,1)])
line([0,V(1,2)],[0,V(2,2)]) 
title('anisotropy axes')
axis equal
pause(1)
       
jac=jacobi(z,lambda);
n=length(znormallambda);
K=covariancematrix(delta,x,y);
[V,D]=eig(K);
invK=V*diag(1./diag(D))*V';

meantransf=(1/sum(invK(:)))*(ones(1,n)*invK*znormallambda)
lambda
deltatransf=delta
A=reshape(A,2,2)
B=A'*A
exitflaglambda=exitflag3

function z=criterium(lambda,zoriginal,zz)
mu=lambda(1);
sigma=lambda(2);
x=zz;                      
pnormal=normaldensity(x,mu,sigma);
ztransformed=transform(zoriginal,lambda(3));
ptransformed=ksdensity(ztransformed,x);
z=sum(((pnormal-ptransformed).^2));
disp([num2str(z),' ',num2str(lambda)])

%Code for plotting the fitting to Normal Distribution(commented):
 figure(1)
 hold off
 plot(x,pnormal) %%%
 hold on
 plot(x,ptransformed,'-r') %%%
 title('kernel density of transformed data')
 hold off
 pause(0.001)
 
 function y=transform(x,lambda)
 x=abs(x);
%Calculates the Box Cox transform
 if ~(lambda==0)
    y=((x.^lambda)-1)/lambda;
 else
    y=log(x);
 end

function z=normaldensity(x,mu,sigma)

z=(1/sqrt(2*pi*sigma^2))*exp(-((x-mu).^2)/(2*sigma^2));

function z=likely(lambda,x,y,zoriginal,delta)
%Maximum Likelihood Estimate for Lambda
znormal=transform(zoriginal,lambda);
jac=jacobi(zoriginal,lambda);
K=covariancematrix(delta,x,y);

[V,D]=eig(K);
D=diag(D);
Jac=sum(log(jac));
n=length(D);
logdetK=sum(log(D));
invK=V*diag(1./D)*V';
a=(1/sum(invK(:)))*(ones(1,n)*invK*znormal);
z= (0.5*logdetK+ 0.5*(znormal-a)'*invK*(znormal-a) - Jac);
disp([num2str(z),' ',num2str(lambda),' ',num2str(delta)])

function z=likely1(delta,x,y,zoriginal,lambda,delta1,estimatedelta)
delta(estimatedelta==0)=delta1;    
%Maximum Likelihood Estimate for Delta
znormal=transform(zoriginal,lambda);
jac=jacobi(zoriginal,lambda);
K=covariancematrix(delta,x,y);

[V,D]=eig(K);
D=diag(D);
Jac=sum(log(jac));
n=length(D);
logdetK=sum(log(D));
invK=V*diag(1./D)*V';
a=(1/sum(invK(:)))*(ones(1,n)*invK*znormal);
z= (0.5*logdetK+ 0.5*(znormal-a)'*invK*(znormal-a) - Jac);
disp([num2str(z),' ',num2str(lambda),' ',num2str(delta)])

function z=likely2(A,x,y,zoriginal,lambda,delta)
%Maximum Likelihood Estimate for A
A=(reshape(A,2,2));
xynew=A*[x';y'];
xnew=xynew(1,:)';
ynew=xynew(2,:)';
znormal=transform(zoriginal,lambda);
jac=jacobi(zoriginal,lambda);
K=covariancematrix(delta,xnew,ynew);

[V,D]=eig(K);
D=diag(D);
Jac=sum(log(jac));
n=length(D);
logdetK=sum(log(D));
invK=V*diag(1./D)*V';
a=(1/sum(invK(:)))*(ones(1,n)*invK*znormal);
z= (0.5*logdetK+ 0.5*(znormal-a)'*invK*(znormal-a) - Jac);
disp([num2str(z),' ',num2str(lambda),' ',num2str(delta),' ',num2str(reshape(A,1,4))])

function cov=covariancematrix(delta,x,y)
%Calculates the Covariance matrix for all pairs of data points
nx=length(x);
for i=1:nx
   for j=i+1:nx
       h=sqrt((x(i)-x(j)).^2+(y(i)-y(j)).^2);
       cov(i,j)=covar(h,delta);
       cov(j,i)=cov(i,j);
   end
   cov(i,i)=covar(0,delta);
end

function cov=covar(h,delta)
%Finds the Covariance for a distance h
if delta(3)==0 
  delta(3)=0.0000000000000001;
end
if delta(4)==0 
  delta(4)=0.0000000000000001;
end

if h==0
  cov=delta(2)+delta(1);
else
  cov=delta(2)*((1-delta(5))*exp(-3*h/delta(3))+delta(5)*exp((-3*h.^2)/(delta(4)^2)));
end

function z=jacobi(x,lambda)
if ~(lambda==0)
  z=abs((x.^(lambda-1)));
else
  z=abs(1./x);
end
